### ISSUE TITLE
demo image receiver not working

### ISSUE THREAD

**Issue by nndays** [quiet/quiet-js#21]
https://quiet.github.io/quiet-js/ gives me this error in Chrome whenever I click on Receive Image/Start Receiver:
```
quiet-emscripten.js:16 Uncaught abort() at Error
    at jsStackTrace (https://quiet.github.io/quiet-js/javascripts/quiet-emscripten.js:1:18181)
    at stackTrace (https://quiet.github.io/quiet-js/javascripts/quiet-emscripten.js:1:18364)
    at abort (https://quiet.github.io/quiet-js/javascripts/quiet-emscripten.js:16:17777)
    at ze (https://quiet.github.io/quiet-js/javascripts/quiet-emscripten.js:6:74856)
    at pc (https://quiet.github.io/quiet-js/javascripts/quiet-emscripten.js:6:23930)
    at Ib (https://quiet.github.io/quiet-js/javascripts/quiet-emscripten.js:6:1450)
    at asm._quiet_decoder_create (https://quiet.github.io/quiet-js/javascripts/quiet-emscripten.js:16:3354)
    at Object.ccallFunc [as ccall] (https://quiet.github.io/quiet-js/javascripts/quiet-emscripten.js:1:8963)
    at Object.receiver (https://quiet.github.io/quiet-js/javascripts/quiet.js:744:30)
    at startReceiver (https://quiet.github.io/quiet-js/javascripts/receiveimage.js:43:48)
```

Otherwise it's a great project, thanks!

Btw if you want to support local usage in Chrome you could allow status 0 in line 108 of quiet.js as Chrome returns status 0 for local xhr:
`  if (this.status >= 200 && this.status < 300) {`
(allow 0 there as well)

**Comment by nndays** [comment]
It also says whenever I call the page:
`quiet-emscripten.js:1 run() called, but dependencies remain, so not running`
